#!/usr/bin/env bash
# check to see  why installation of Ubuntu container Nginx  is not listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
